name: vaultify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: any
  google_fonts: any
  intl: any

  sqflite: any
  path: any

  shared_preferences: any
  font_awesome_flutter: any

  flutter_slidable: any
  google_nav_bar: any
  avatar_glow: any
  progress_indicators: any
  url_launcher: any

  iconly: any
  flutter_screenutil: any
  cupertino_icons: any
  loading_animation_widget: any

  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  google_sign_in: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
